# 基础镜像
FROM redis
# author
MAINTAINER easyai

# 挂载目录
VOLUME /home/easyai/redis
# 创建目录
RUN mkdir -p /home/easyai/redis
# 指定路径
WORKDIR /home/easyai/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/easyai/redis/redis.conf
