# 基础镜像
FROM eclipse-temurin:23-jre-alpine
# author
MAINTAINER easyai

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/easyai-gateway.jar /home/ruoyi/easyai-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","easyai-gateway.jar"]