# 基础镜像
FROM nginx
# author
MAINTAINER easyai
# 创建目录
RUN mkdir -p /home/easyai/projects/easyai-ui
# 指定路径
WORKDIR /home/easyai/projects/easyai-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/easyai/projects/easyai-ui
