# 基础镜像
FROM eclipse-temurin:23-jre-alpine
# author
MAINTAINER easyai

# 挂载目录
VOLUME /home/easyai
# 创建目录
RUN mkdir -p /home/easyai
# 指定路径
WORKDIR /home/easyai
# 复制jar文件到路径
COPY ./jar/easyai-modules-job.jar /home/easyai/easyai-modules-job.jar
# 启动定时任务服务
ENTRYPOINT ["java","-jar","easyai-modules-job.jar"]